name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'  # Isso significa qualquer branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'   # Configurando para Java 17
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: |
          mvn clean test  
  

  build_docker:
    runs-on: ubuntu-latest
    needs: continuous-integration  # Esse job depende do anterior

    if: success()

    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
