name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'  # Isso significa qualquer branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'   # Configurando para Java 17
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: |
          mvn clean test  
          

  build_docker:
    runs-on: ubuntu-latest
    needs: continuous-integration  # Esse job depende do anterior

    if: success()

    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."

#      - name: Log in to Azure Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ secrets.REGISTRY_URL }}
#          username: ${{ secrets.REGISTRY_USERNAME }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}
#
#      - name: Build Docker images with Docker Compose
#        run: |
#          docker-compose -f docker-compose.yml build
#
#      - name: Push Docker images to Azure Container Registry
#        run: |
#          docker-compose -f docker-compose.yml push
#
#  deploy_test:
#    runs-on: ubuntu-latest
#    needs: build_docker  # Esse job depende do job de build_docker
#    if: success()  # Só será executado se o job anterior for bem-sucedido
#
#    steps:
#      - name: Azure Web Apps Deploy Test
#        uses: Azure/webapps-deploy@v2
#        with:
#          app-name: ${{ secrets.AZURE_TEST_APP_NAME }}
#          publish-profile: ${{ secrets.AZURE_TEST_PUBLISH_PROFILE }}
#          images: ${{ secrets.REGISTRY_URL }}/smartcity-waste-management:latest
