name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: |
          mvn clean install  # Compila e executa testes
          mvn test           # Executa os testes

  build_docker:
    runs-on: ubuntu-latest
    needs: build_and_test  # Depende da execução de build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_URL }}/smartcity-waste-management:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/smartcity-waste-management:latest
