name: Continuous Integration

on:
  pull_request:  # Aciona para pull requests
  push:          # Aciona para pushs
    branches:
      - '*'  # Isso significa qualquer branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'   # Configura o Java 17 para o seu projeto
          distribution: 'temurin'

      - name: Build and test
        run: mvn clean test # Este comando vai rodar os testes

      - name: Build Java application
        run: mvn clean package # Gera o diretório target e o JAR

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration  # Este job depende do anterior
    if: success()  # Só executará se o job anterior for bem-sucedido
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use seu nome de usuário do Docker Hub nos segredos do GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use seu token de acesso do Docker Hub nos segredos do GitHub

      - name: Build Docker image
        run: docker build -t helionay/cadastrousuarios:v1 .

      - name: Push Docker image
        run: docker push helionay/cadastrousuarios:v1

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Adicione aqui seu comando de deploy, como comandos para o Azure se aplicável
