name: Continuous Integration

on:
  pull_request:  # Aciona para pull requests
  push:          # Aciona para pushs
    branches:
      - '*'  # Qualquer branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Configurado para Java 17
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: |
          mvn clean install   # Constrói o projeto e gera o arquivo .jar
          mvn test            # Executa os testes

  build_docker:
    runs-on: ubuntu-latest
    needs: continuous-integration  # Esse job depende do job anterior

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker container
        run: |
          docker-compose -f docker-compose.yml up -d
