name: CI/CD Pipeline for Test Environment

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: |
          mvn clean package -DskipTests=false

      - name: Save JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  build_docker:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image for Test
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/smart-waste-management-test:latest .
          docker push ${{ secrets.REGISTRY_URL }}/smart-waste-management-test:latest

  deploy_test:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Azure Web Apps Deploy for Test
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_TEST_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_TEST_PUBLISH_PROFILE }}
          images: DOCKER|${{ secrets.REGISTRY_URL }}/smart-waste-management-test:latest
